services:
  ollama:
    environment:
      OLLAMA_NUM_PARALLEL: ${OLLAMA_NUM_PARALLEL}

  speech:
    environment:
      WHISPER_DEVICE: ${WHISPER_DEVICE}
      WHISPER_COMPUTE_TYPE: ${WHISPER_COMPUTE_TYPE}
